# ----------------------------------------------------------------------
# |
# |  Copyright (c) 2024 Scientific Software Engineering Center at Georgia Tech
# |  Distributed under the MIT License.
# |
# ----------------------------------------------------------------------
name: "Standard"

run-name: ${{ github.run_number }} [${{ github.actor }}] on ${{ github.ref_name }}

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Once a day at 12am UTC
  workflow_dispatch:

jobs:
  # ----------------------------------------------------------------------
  action_contexts:
    name: "Display GitHub Action Contexts"
    uses: davidbrownell/dbrownell_DevTools/.github/workflows/callable_display_action_contexts.yaml@main

  # ----------------------------------------------------------------------
  validate:
    strategy:
      fail-fast: false

      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

        python_version:
          - "3.12"
          - "3.11"
          - "3.10"
          # - "3.9"  # Not supported
          # - "3.8"  # Not supported

    name: Validate

    uses: davidbrownell/dbrownell_DevTools/.github/workflows/callable_validate_python.yaml@main
    with:
      operating_system: ${{ matrix.os }}
      python_version: ${{ matrix.python_version }}

  # ----------------------------------------------------------------------
  package_coverage:
    needs: validate

    name: Postprocess Coverage Info
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

    uses: davidbrownell/dbrownell_DevTools/.github/workflows/callable_package_python_coverage.yaml@main
    with:
      gist_id: 2f9d770d13e3a148424f374f74d41f4b
      gist_filename: PythonProjectBootstrapperTest2_coverage.json
    secrets:
      GIST_TOKEN: ${{ secrets.GIST_TOKEN }}

# BugBug: Begin
  # ----------------------------------------------------------------------
  package_coverage_bugbug:
    needs: validate

    name: Postprocess Coverage Info (BugBug)

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Source"
        uses: actions/checkout@v4

      - name: Download Coverage Data
        uses: actions/download-artifact@v4
        with:
          path: stage
          merge-multiple: true

      - name: Bootstrap
        shell: bash
        run: |
          ./Bootstrap.sh

      - name: Combine
        shell: bash
        run: |
          . ./Activate.sh

          coverage combine stage
          coverage report --ignore-errors --show-missing --skip-covered
          coverage json --ignore-errors

          export TOTAL=$(python -c "import json;print(json.load(open('coverage.json'))['totals']['percent_covered_display'])")
          echo "total=$TOTAL" >> $GITHUB_ENV
          echo "### Total coverage: ${TOTAL}%" >> $GITHUB_STEP_SUMMARY

      - name: Write File
        shell: bash
        run: |
          echo "{\"label\":\"Coverage\",\"message\":\"--81%--\",\"schemaVersion\":1,\"color\":\"hsl(93, 100%, 40%)\"}" >> __code_coverage_badge_info.json

      - name: Upload Archive
        uses: actions/upload-artifact@v4
        with:
          name: __code_coverage_badge_info.json
          path: __code_coverage_badge_info.json
          compression-level: 0
# BugBug: End

  # ----------------------------------------------------------------------
  create_package:
    needs: validate

    strategy:
      fail-fast: false

      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

        python_version:
          - "3.12"
          - "3.11"
          - "3.10"
          # - "3.9"  # Not supported
          # - "3.8"  # Not supported

    name: Create Package

    uses: davidbrownell/dbrownell_DevTools/.github/workflows/callable_create_python_package.yaml@main
    with:
      operating_system: ${{ matrix.os }}
      python_version: ${{ matrix.python_version }}

  # ----------------------------------------------------------------------
  validate_package:
    needs: create_package

    strategy:
      fail-fast: false

      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

        python_version:
          - "3.12"
          - "3.11"
          - "3.10"
          # - "3.9"  # Not supported
          # - "3.8"  # Not supported

    name: Validate Package

    uses: davidbrownell/dbrownell_DevTools/.github/workflows/callable_validate_python_package.yaml@main
    with:
      operating_system: ${{ matrix.os }}
      python_version: ${{ matrix.python_version }}
      validation_command: python -c "from PythonProjectBootstrapperTest2 import __version__; print(__version__)"

  # ----------------------------------------------------------------------
  create_binary:
    needs: validate

    strategy:
      fail-fast: false

      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

        python_version:
          - "3.11"

    name: Create Binary

    uses: davidbrownell/dbrownell_DevTools/.github/workflows/callable_create_python_binary.yaml@main
    with:
      operating_system: ${{ matrix.os }}
      python_version: ${{ matrix.python_version }}

  # ----------------------------------------------------------------------
  validate_binary:
    needs: create_binary

    strategy:
      fail-fast: false

      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

        python_version:
          - "3.11"

    name: Validate Binary

    uses: davidbrownell/dbrownell_DevTools/.github/workflows/callable_validate_python_binary.yaml@main
    with:
      operating_system: ${{ matrix.os }}
      python_version: ${{ matrix.python_version }}
      validation_command: PythonProjectBootstrapperTest2 Version


# ----------------------------------------------------------------------
  create_docker_image:
    needs:
      - validate_package
      - validate_binary

    strategy:
      fail-fast: false

      matrix:
        python_version:
          - "3.12"
          - "3.11"
          - "3.10"
          # - "3.9"  # Not supported
          # - "3.8"  # Not supported

    name: Create Docker Image

    uses: davidbrownell/dbrownell_DevTools/.github/workflows/callable_create_docker_image.yaml@main
    with:
      operating_system: ubuntu-latest
      python_version: ${{ matrix.python_version }}
      name_suffix: -${{ matrix.python_version }}
      bootstrap_args: ""
      docker_description: "PythonProjectBootstrapperTest2 - ${{ matrix.python_version }}"
      push_image_as_package: true
      container_registry_username: gt-sse-center


  # ----------------------------------------------------------------------
  publish:
    needs:

      - create_docker_image


    name: Publish

    uses: davidbrownell/dbrownell_DevTools/.github/workflows/callable_publish_python.yaml@main
    with:
      release_sources_configuration_filename: .github/release_sources.yaml
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
